/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RelapseRouteImport } from './routes/relapse'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CravingsRouteImport } from './routes/cravings'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RelapseRoute = RelapseRouteImport.update({
  id: '/relapse',
  path: '/relapse',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CravingsRoute = CravingsRouteImport.update({
  id: '/cravings',
  path: '/cravings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/coach': typeof CoachRoute
  '/cravings': typeof CravingsRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/plus': typeof PlusRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/refund': typeof RefundRoute
  '/relapse': typeof RelapseRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/coach': typeof CoachRoute
  '/cravings': typeof CravingsRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/plus': typeof PlusRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/refund': typeof RefundRoute
  '/relapse': typeof RelapseRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/coach': typeof CoachRoute
  '/cravings': typeof CravingsRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/plus': typeof PlusRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/refund': typeof RefundRoute
  '/relapse': typeof RelapseRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/checkin'
    | '/coach'
    | '/cravings'
    | '/explore'
    | '/insights'
    | '/journal'
    | '/library'
    | '/plus'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/refund'
    | '/relapse'
    | '/reminders'
    | '/settings'
    | '/sos'
    | '/terms'
    | '/today'
    | '/api/chat'
    | '/checkout/success'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/checkin'
    | '/coach'
    | '/cravings'
    | '/explore'
    | '/insights'
    | '/journal'
    | '/library'
    | '/plus'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/refund'
    | '/relapse'
    | '/reminders'
    | '/settings'
    | '/sos'
    | '/terms'
    | '/today'
    | '/api/chat'
    | '/checkout/success'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/checkin'
    | '/coach'
    | '/cravings'
    | '/explore'
    | '/insights'
    | '/journal'
    | '/library'
    | '/plus'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/refund'
    | '/relapse'
    | '/reminders'
    | '/settings'
    | '/sos'
    | '/terms'
    | '/today'
    | '/api/chat'
    | '/checkout/success'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  CoachRoute: typeof CoachRoute
  CravingsRoute: typeof CravingsRoute
  ExploreRoute: typeof ExploreRoute
  InsightsRoute: typeof InsightsRoute
  JournalRoute: typeof JournalRoute
  LibraryRoute: typeof LibraryRoute
  PlusRoute: typeof PlusRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RefundRoute: typeof RefundRoute
  RelapseRoute: typeof RelapseRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  TermsRoute: typeof TermsRoute
  TodayRoute: typeof TodayRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relapse': {
      id: '/relapse'
      path: '/relapse'
      fullPath: '/relapse'
      preLoaderRoute: typeof RelapseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cravings': {
      id: '/cravings'
      path: '/cravings'
      fullPath: '/cravings'
      preLoaderRoute: typeof CravingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  CoachRoute: CoachRoute,
  CravingsRoute: CravingsRoute,
  ExploreRoute: ExploreRoute,
  InsightsRoute: InsightsRoute,
  JournalRoute: JournalRoute,
  LibraryRoute: LibraryRoute,
  PlusRoute: PlusRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RefundRoute: RefundRoute,
  RelapseRoute: RelapseRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  TermsRoute: TermsRoute,
  TodayRoute: TodayRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
